PU2CLR Si4735 Arduino Library: Host and slave MCU setup
Host and slave MCU setup
Functions
void SI4735::setMaxDelayPowerUp (uint16_t ms)
Set the Max Delay Power Up.
void SI4735::reset (void)
Reset the SI473X
void SI4735::waitToSend (void)
Wait for the si473x is ready (Clear to Send (CTS) status bit have to be 1).
void SI4735::setPowerUp (uint8_t CTSIEN, uint8_t GPO2OEN, uint8_t PATCH, uint8_t XOSCEN, uint8_t FUNC, uint8_t OPMODE)
Set the Power Up parameters for si473X.
void SI4735::radioPowerUp (void)
Powerup the Si47XX.
void SI4735::analogPowerUp (void)
You have to call setPowerUp method before.
void SI4735::powerDown (void)
Moves the device from powerup to powerdown mode.
Detailed Description
Function Documentation
setMaxDelayPowerUp()
void SI4735::setMaxDelayPowerUp (uint16_t ms) inline
Set the Max Delay Power Up.
Sets the delay needed in ms after a powerup command (default is 10ms).
Some external crystal might need more time to become stable (500 ms is the recommended).
Low values make the load SSB patch faster. However, it can make the system unstable.
See also
MAX_DELAY_AFTER_POWERUP
Parameters
ms delay in ms
reset()
void SI4735::reset (void)
Reset the SI473X
See also
Si47XX PROGRAMMING GUIDE; AN332;
Referenced by SI4735::getDeviceI2CAddress(), SI4735::setup(), and SI4735::ssbSetup().
waitToSend()
void SI4735::waitToSend (void)
Wait for the si473x is ready (Clear to Send (CTS) status bit have to be 1).
This function should be used before sending any command to a SI47XX device.
See also
Si47XX PROGRAMMING GUIDE; AN332; pages 63, 128
Referenced by SI4735::downloadPatch(), SI4735::getAutomaticGainControl(), SI4735::getCurrentReceivedSignalQuality(), SI4735::getFirmware(), SI4735::getInterruptStatus(), SI4735::getProperty(), SI4735::getRdsStatus(), SI4735::getStatus(), SI4735::patchPowerUp(), SI4735::powerDown(), SI4735::queryLibraryId(), SI4735::radioPowerUp(), SI4735::seekStation(), SI4735::sendCommand(), SI4735::sendProperty(), SI4735::sendSSBModeProperty(), SI4735::setAutomaticGainControl(), SI4735::setBandwidth(), SI4735::setFrequency(), SI4735::setGpio(), SI4735::setGpioCtl(), SI4735::setRdsConfig(), SI4735::setRdsIntSource(), SI4735::setSSBBfo(), and SI4735::ssbPowerUp().
setPowerUp()
void SI4735::setPowerUp (uint8_t CTSIEN, uint8_t GPO2OEN, uint8_t PATCH, uint8_t XOSCEN, uint8_t FUNC, uint8_t OPMODE)
Set the Power Up parameters for si473X.
Use this method to chenge the defaul behavior of the Si473X. Use it before PowerUp()
See also
Si47XX PROGRAMMING GUIDE; AN332; pages 65 and 129
Parameters
uint8_t CTSIEN sets Interrupt anabled or disabled (1 = anabled and 0 = disabled)
uint8_t GPO2OEN sets GP02 Si473X pin enabled (1 = anabled and 0 = disabled)
uint8_t PATCH Used for firmware patch updates. Use it always 0 here.
uint8_t XOSCEN sets external Crystal enabled or disabled
uint8_t FUNC sets the receiver function have to be used [0 = FM Receive; 1 = AM (LW/MW/SW) and SSB (if SSB patch apllied)]
uint8_t OPMODE set the kind of audio mode you want to use.
radioPowerUp()
void SI4735::radioPowerUp (void)
Powerup the Si47XX.
Before call this function call the setPowerUp to set up the parameters.
Parameters you have to set up with setPowerUp
Parameter Description
CTSIEN Interrupt anabled or disabled
GPO2OEN GPO2 Output Enable or disabled
PATCH Boot normally or patch
XOSCEN Use external crystal oscillator
FUNC defaultFunction = 0 = FM Receive; 1 = AM (LW/MW/SW) Receiver
OPMODE SI473X_ANALOG_AUDIO (B00000101) or SI473X_DIGITAL_AUDIO (B00001011)
See also
setMaxDelaySetFrequency()
MAX_DELAY_AFTER_POWERUP
SI4735::setPowerUp()
Si47XX PROGRAMMING GUIDE; AN332; pages 64, 129
References SI4735::setHardwareAudioMute(), and SI4735::waitToSend().
Referenced by SI4735::analogPowerUp(), SI4735::setAM(), SI4735::setFM(), SI4735::setSSB(), and SI4735::setup().
analogPowerUp()
void SI4735::analogPowerUp (void)
You have to call setPowerUp method before.
This function is still available only for legacy reasons. If you are using this function, please, replace it by radioPowerup().
Deprecated:
Use radioPowerUp instead.
See also
SI4735::setPowerUp()
Si47XX PROGRAMMING GUIDE; AN332; pages 64, 129
References SI4735::radioPowerUp().
powerDown()
void SI4735::powerDown (void)
Moves the device from powerup to powerdown mode.
After Power Down command, only the Power Up command is accepted.
See also
Si47XX PROGRAMMING GUIDE; AN332; pages 67, 132
radioPowerUp()
References SI4735::setHardwareAudioMute(), and SI4735::waitToSend().
Referenced by SI4735::queryLibraryId(), SI4735::setAM(), and SI4735::setFM().