PU2CLR Si4735 Arduino Library: Frequency and Device status
Frequency and Device status
Functions
uint16_t SI4735::getCurrentFrequency ()
Gets the current frequency saved in memory.
void SI4735::getStatus ()
Gets the current status of the Si47XX (AM, FM or SSB)
uint16_t SI4735::getFrequency (void)
Gets the current frequency of the Si4735 (AM or FM)
void SI4735::getStatus (uint8_t, uint8_t)
Gets the current status of the Si4735 (AM or FM)
void SI4735::getAutomaticGainControl ()
Queries Automatic Gain Control STATUS.
void SI4735::setAutomaticGainControl (uint8_t AGCDIS, uint8_t AGCIDX)
Automatic Gain Control setup.
void SI4735::setAvcAmMaxGain (uint8_t gain)
Sets the maximum gain for automatic volume control.
void SI4735::getCurrentReceivedSignalQuality (uint8_t INTACK)
Queries the status of the Received Signal Quality (RSQ) of the current channel.
void SI4735::getCurrentReceivedSignalQuality (void)
Queries the status of the Received Signal Quality (RSQ) of the current channel (FM_RSQ_STATUS)
Detailed Description
Function Documentation
getCurrentFrequency()
uint16_t SI4735::getCurrentFrequency () inline
Gets the current frequency saved in memory.
Unlike getFrequency, this method gets the current frequency recorded after the last setFrequency command.
This method avoids bus traffic and CI processing.
However, you can not get others status information like RSSI.
See also
getFrequency()
getStatus() [1/2]
void SI4735::getStatus () inline
Gets the current status of the Si47XX (AM, FM or SSB)
See also
Si47XX PROGRAMMING GUIDE; AN332 (REV 1.0); pages 73 (FM) and 139 (AM)
getFrequency()
uint16_t SI4735::getFrequency (void)
Gets the current frequency of the Si4735 (AM or FM)
Device Status Information
The method status do it an more. See getStatus below.
See also
Si47XX PROGRAMMING GUIDE; AN332 (REV 1.0); pages 73 (FM) and 139 (AM)
getStatus() [2/2]
void SI4735::getStatus (uint8_t INTACK, uint8_t CANCEL)
Gets the current status of the Si4735 (AM or FM)
See also
Si47XX PROGRAMMING GUIDE; AN332 (REV 1.0); pages 73 (FM) and 139 (AM)
Parameters
uint8_t INTACK Seek/Tune Interrupt Clear. If set, clears the seek/tune complete interrupt status indicator;
uint8_t CANCEL Cancel seek. If set, aborts a seek currently in progress;
References SI4735::waitToSend().
getAutomaticGainControl()
void SI4735::getAutomaticGainControl ()
Queries Automatic Gain Control STATUS.
After call this method, you can call isAgcEnabled to know the AGC status and getAgcGainIndex to know the gain index value.
See also
Si47XX PROGRAMMING GUIDE; AN332 (REV 1.0); For FM page 80; for AM page 142.
AN332 REV 0.8 Universal Programming Guide Amendment for SI4735-D60 SSB and NBFM patches; page 18.
References SI4735::waitToSend().
setAutomaticGainControl()
void SI4735::setAutomaticGainControl (uint8_t AGCDIS, uint8_t AGCIDX)
Automatic Gain Control setup.
If FM, overrides AGC setting by disabling the AGC and forcing the LNA to have a certain gain that ranges between 0 (minimum attenuation) and 26 (maximum attenuation).
If AM/SSB, Overrides the AGC setting by disabling the AGC and forcing the gain index that ranges between 0 (minimum attenuation) and 37+ATTN_BACKUP (maximum attenuation).
See also
Si47XX PROGRAMMING GUIDE; AN332 (REV 1.0); For FM page 81; for AM page 143
Parameters
uint8_t AGCDIS This param selects whether the AGC is enabled or disabled (0 = AGC enabled; 1 = AGC disabled);
uint8_t AGCIDX AGC Index (0 = Minimum attenuation (max gain); 1 – 36 = Intermediate attenuation); if >greater than 36 - Maximum attenuation (min gain)).
References SI4735::waitToSend().
setAvcAmMaxGain()
void SI4735::setAvcAmMaxGain (uint8_t gain)
Sets the maximum gain for automatic volume control.
If no parameter is sent, it will be consider 48dB.
See also
Si47XX PROGRAMMING GUIDE; AN332 (REV 1.0); page 152
setAvcAmMaxGain()
Parameters
uint8_t gain Select a value between 12 and 192. Defaul value 48dB.
getCurrentReceivedSignalQuality() [1/2]
void SI4735::getCurrentReceivedSignalQuality (uint8_t INTACK)
Queries the status of the Received Signal Quality (RSQ) of the current channel.
This method sould be called berore call getCurrentRSSI(), getCurrentSNR() etc. Command FM_RSQ_STATUS
See also
Si47XX PROGRAMMING GUIDE; AN332 (REV 1.0); pages 75 and 141
Parameters
INTACK Interrupt Acknowledge. 0 = Interrupt status preserved; 1 = Clears RSQINT, BLENDINT, SNRHINT, SNRLINT, RSSIHINT, RSSILINT, MULTHINT, MULTLINT.
References SI4735::waitToSend().
getCurrentReceivedSignalQuality() [2/2]
void SI4735::getCurrentReceivedSignalQuality (void)
Queries the status of the Received Signal Quality (RSQ) of the current channel (FM_RSQ_STATUS)
See also
Si47XX PROGRAMMING GUIDE; AN332 (REV 1.0); pages 75 and 141
Parameters
INTACK Interrupt Acknowledge. 0 = Interrupt status preserved; 1 = Clears RSQINT, BLENDINT, SNRHINT, SNRLINT, RSSIHINT, RSSILINT, MULTHINT, MULTLINT.